packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 1440
blockExoticSubdeps: true

allowBuilds:
  '@swc/core': true
  esbuild: true
  core-js: false

overrides:
  webpackbar: 7.0.0
  uuid: ^14.0.0
  ip-address: ^10.1.1
  serialize-javascript: ^7.0.5
  fast-uri: ^3.1.2
  hono: ^4.12.18
  '@babel/plugin-transform-modules-systemjs': ^7.29.4

patchedDependencies:
  '@terrazzo/plugin-css-in-js@2.0.3': patches/@terrazzo__plugin-css-in-js@2.0.3.patch
