import { dirname } from 'node:path';
import { loadProject } from '@unpunnyfuns/swatchbook-core';
import { resolverPath, tokensDir } from '@unpunnyfuns/swatchbook-tokens';
import { beforeAll, expect, it } from 'vitest';
import cssInJsIntegration, { renderTheme } from '#/css-in-js.ts';
import type { Project } from '@unpunnyfuns/swatchbook-core';

let project: Project;

beforeAll(async () => {
  project = await loadProject({ resolver: resolverPath, cssVarPrefix: 'sb' }, dirname(tokensDir));
});

it('integration exposes virtual:swatchbook/theme by default', () => {
  const integration = cssInJsIntegration();
  expect(integration.name).toBe('css-in-js');
  expect(integration.virtualModule?.virtualId).toBe('virtual:swatchbook/theme');
});

it('emits top-level exports per $type group, plus an aggregate `theme`', () => {
  const js = renderTheme(project);
  expect(js).toMatch(/^export const color =/m);
  expect(js).toMatch(/^export const typography =/m);
  expect(js).toMatch(/^export const theme = \{ /m);
  expect(js).toContain('color');
  expect(js).toContain('typography');
});

it('leaves resolve to var() references carrying the project prefix', () => {
  const js = renderTheme(project);
  expect(js).toContain('"var(--sb-color-surface-default)"');
  expect(js).toContain('"var(--sb-color-palette-neutral-500)"');
});

it('drops the dash when cssVarPrefix is empty', async () => {
  const bare = await loadProject({ resolver: resolverPath, cssVarPrefix: '' }, dirname(tokensDir));
  const js = renderTheme(bare);
  expect(js).toContain('"var(--color-surface-default)"');
  expect(js).not.toContain('--sb-');
});

it('quotes dashed keys and leaves numeric-canonical keys bare', () => {
  const js = renderTheme(project);
  // Dashed: `bg-hover` must be quoted.
  expect(js).toContain('"bg-hover":');
  // Numeric canonical: `500` should render bare inside the palette tree.
  expect(js).toMatch(/\b500: "var\(--sb-color-palette-neutral-500\)"/);
});

it('output starts with a banner pointing at the package', () => {
  const js = renderTheme(project);
  expect(js).toMatch(/^\/\* Generated by @unpunnyfuns\/swatchbook-integrations\/css-in-js\./);
});
