import { dirname } from 'node:path';
import { loadProject } from '@unpunnyfuns/swatchbook-core';
import { resolverPath, tokensDir } from '@unpunnyfuns/swatchbook-tokens';
import { beforeAll, expect, it } from 'vitest';
import tailwindIntegration, { renderTailwindTheme } from '#/tailwind.ts';
import type { Project } from '@unpunnyfuns/swatchbook-core';

let project: Project;

beforeAll(async () => {
  project = await loadProject({ resolver: resolverPath, cssVarPrefix: 'sb' }, dirname(tokensDir));
});

it('integration exposes virtual:swatchbook/tailwind.css by default', () => {
  const integration = tailwindIntegration();
  expect(integration.name).toBe('tailwind');
  expect(integration.virtualModule?.virtualId).toBe('virtual:swatchbook/tailwind.css');
});

it('@theme block carries cssVarPrefix on both sides of every alias', () => {
  const css = renderTailwindTheme(project);
  // Tailwind-namespace side (left) and swatchbook-namespace side (right) are both prefixed.
  expect(css).toContain('--color-sb-surface-default: var(--sb-color-surface-default);');
  expect(css).toContain('--spacing-sb-md: var(--sb-space-md);');
  expect(css).toContain('--radius-sb-lg: var(--sb-radius-lg);');
  expect(css).toContain('--shadow-sb-md: var(--sb-shadow-md);');
});

it('output starts with a banner and @import tailwindcss', () => {
  const css = renderTailwindTheme(project);
  expect(css).toMatch(/^\/\* Generated by @unpunnyfuns\/swatchbook-integrations\/tailwind/);
  expect(css).toContain("@import 'tailwindcss';");
  expect(css).toContain('@theme {');
  expect(css).toContain('}');
});

it('drops the dash when cssVarPrefix is empty', async () => {
  const bare = await loadProject({ resolver: resolverPath, cssVarPrefix: '' }, dirname(tokensDir));
  const css = renderTailwindTheme(bare);
  // No `sb-` segment on either side.
  expect(css).toContain('--color-surface-default: var(--color-surface-default);');
  expect(css).not.toContain('--sb-');
});

it('accepts a custom role map replacing the default', () => {
  const css = renderTailwindTheme(project, {
    color: [['only-accent', 'color.accent.bg']],
  });
  expect(css).toContain('--color-sb-only-accent: var(--sb-color-accent-bg);');
  // Default roles should not appear with a custom map.
  expect(css).not.toContain('--color-sb-surface-default:');
  expect(css).not.toContain('--spacing-sb-md:');
});
