import type { Project } from '@unpunnyfuns/swatchbook-core';
import { describe, expect, it } from 'vitest';
import { renderTokenTypes } from '#/preset.ts';

function fakeProject(partial: Partial<Project>): Project {
  return {
    config: { cssVarPrefix: 'sb' },
    axes: [],
    disabledAxes: [],
    presets: [],
    themes: [],
    themesResolved: {},
    graph: {},
    sourceFiles: [],
    diagnostics: [],
    ...partial,
  } as Project;
}

describe('renderTokenTypes', () => {
  it('emits a do-not-edit banner + module augmentation', () => {
    const out = renderTokenTypes(fakeProject({}));
    expect(out).toContain('// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.');
    expect(out).toContain("declare module '@unpunnyfuns/swatchbook-addon/hooks'");
    expect(out).toContain('interface SwatchbookTokenMap {');
  });

  it('sorts token paths alphabetically across themes', () => {
    const project = fakeProject({
      themes: [
        { name: 'Light', input: {}, sources: [] },
        { name: 'Dark', input: {}, sources: [] },
      ],
      themesResolved: {
        Light: {
          'color.sys.bg': { id: 'color.sys.bg' } as never,
          'color.sys.fg': { id: 'color.sys.fg' } as never,
        },
        Dark: {
          'color.sys.accent': { id: 'color.sys.accent' } as never,
          'color.sys.bg': { id: 'color.sys.bg' } as never,
        },
      },
    });
    const out = renderTokenTypes(project);
    const bgIdx = out.indexOf('"color.sys.bg"');
    const accentIdx = out.indexOf('"color.sys.accent"');
    const fgIdx = out.indexOf('"color.sys.fg"');
    expect(accentIdx).toBeLessThan(bgIdx);
    expect(bgIdx).toBeLessThan(fgIdx);
  });

  it('builds SwatchbookThemeName as a union of theme names', () => {
    const project = fakeProject({
      themes: [
        { name: 'Light', input: {}, sources: [] },
        { name: 'Dark', input: {}, sources: [] },
      ],
    });
    const out = renderTokenTypes(project);
    expect(out).toContain('export type SwatchbookThemeName = "Light" | "Dark";');
  });

  it('falls back to string when no themes exist', () => {
    const out = renderTokenTypes(fakeProject({}));
    expect(out).toContain('export type SwatchbookThemeName = string;');
  });

  it('dedupes token paths across themes', () => {
    const project = fakeProject({
      themes: [
        { name: 'Light', input: {}, sources: [] },
        { name: 'Dark', input: {}, sources: [] },
      ],
      themesResolved: {
        Light: { 'color.bg': { id: 'color.bg' } as never },
        Dark: { 'color.bg': { id: 'color.bg' } as never },
      },
    });
    const out = renderTokenTypes(project);
    const hits = (out.match(/"color\.bg": string;/g) ?? []).length;
    expect(hits).toBe(1);
  });
});
