// Pragmatic exception: `renderTokenTypes` is not part of the public API,
// but its real "surface" is the generated `.swatchbook/tokens.d.ts` file
// consumed by TypeScript during `useToken()` autocompletion. Testing the
// pure function is materially cheaper than a full codegen-write-read-parse
// round-trip while asserting the same observable output. If the signature
// ever changes, this test should move to a snapshot of the written file.
import type { Project, VarianceInfo } from '@unpunnyfuns/swatchbook-core';
import { expect, it } from 'vitest';
import { renderTokenTypes } from '#/preset.ts';

function fakeProject(partial: Partial<Project>): Project {
  return {
    config: { cssVarPrefix: 'sb' },
    axes: [],
    disabledAxes: [],
    presets: [],
    cells: {},
    jointOverrides: [],
    defaultTokens: {},
    defaultTuple: {},
    resolveAt: () => ({}),
    varianceByPath: new Map(),
    sourceFiles: [],
    listing: {},
    diagnostics: [],
    cwd: '',
    chrome: {},
    ...partial,
  } as Project;
}

function variance(paths: readonly string[]): ReadonlyMap<string, VarianceInfo> {
  const out = new Map<string, VarianceInfo>();
  for (const p of paths) {
    out.set(p, { kind: 'baseline-only' } as VarianceInfo);
  }
  return out;
}

it('emits a do-not-edit banner + module augmentation', () => {
  const out = renderTokenTypes(fakeProject({}));
  expect(out).toContain('// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.');
  expect(out).toContain("declare module '@unpunnyfuns/swatchbook-addon/hooks'");
  expect(out).toContain('interface SwatchbookTokenMap {');
});

it('sorts token paths alphabetically', () => {
  const project = fakeProject({
    varianceByPath: variance(['color.bg', 'color.fg', 'color.accent']),
  });
  const out = renderTokenTypes(project);
  const bgIdx = out.indexOf('"color.bg"');
  const accentIdx = out.indexOf('"color.accent"');
  const fgIdx = out.indexOf('"color.fg"');
  expect(accentIdx).toBeLessThan(bgIdx);
  expect(bgIdx).toBeLessThan(fgIdx);
});

it('builds SwatchbookPermutationName as a union of singleton theme names from axes + defaultTuple', () => {
  const project = fakeProject({
    axes: [
      {
        name: 'mode',
        contexts: ['Light', 'Dark'],
        default: 'Light',
        source: 'resolver',
      },
    ],
    defaultTuple: { mode: 'Light' },
  });
  const out = renderTokenTypes(project);
  expect(out).toContain('export type SwatchbookPermutationName = "Light" | "Dark";');
});

it('falls back to string when no axes are present', () => {
  const out = renderTokenTypes(fakeProject({}));
  expect(out).toContain('export type SwatchbookPermutationName = string;');
});

it('includes preset tuples in the theme name union', () => {
  const project = fakeProject({
    axes: [
      { name: 'mode', contexts: ['Light', 'Dark'], default: 'Light', source: 'resolver' },
      {
        name: 'brand',
        contexts: ['Default', 'BrandA'],
        default: 'Default',
        source: 'resolver',
      },
    ],
    defaultTuple: { mode: 'Light', brand: 'Default' },
    presets: [{ name: 'Dark BrandA', axes: { mode: 'Dark', brand: 'BrandA' } }],
  });
  const out = renderTokenTypes(project);
  expect(out).toContain('"Dark · BrandA"');
});

it('emits each path once even when surfaced multiple times in varianceByPath', () => {
  const project = fakeProject({
    varianceByPath: variance(['color.bg', 'color.bg']),
  });
  const out = renderTokenTypes(project);
  const hits = (out.match(/"color\.bg": string;/g) ?? []).length;
  expect(hits).toBe(1);
});
