// Pragmatic exception: `renderTokenTypes` is not part of the public API,
// but its real "surface" is the generated `.swatchbook/tokens.d.ts` file
// consumed by TypeScript during `useToken()` autocompletion. Testing the
// pure function is materially cheaper than a full codegen-write-read-parse
// round-trip while asserting the same observable output. If the signature
// ever changes, this test should move to a snapshot of the written file.
import type { Project } from '@unpunnyfuns/swatchbook-core';
import type { TokenGraph } from '@unpunnyfuns/swatchbook-core/graph';
import { expect, it } from 'vitest';
import { renderTokenTypes } from '#/token-codegen.ts';

function emptyGraph(paths: readonly string[] = []): TokenGraph {
  const nodes: TokenGraph['nodes'] = {};
  for (const path of paths) {
    nodes[path] = {
      baselineValue: { $type: 'color', $value: { colorSpace: 'srgb', components: [0, 0, 0] } },
      baselineKind: 'literal',
      writes: {},
      aliases: [],
      aliasedBy: [],
      affectedBy: [],
    };
  }
  return { nodes, axes: [], axisDefaults: {}, axisContexts: {} };
}

function fakeProject(partial: Partial<Project>): Project {
  return {
    config: { cssVarPrefix: 'sb' },
    axes: [],
    disabledAxes: [],
    presets: [],
    defaultTokens: {},
    defaultTuple: {},
    resolveAt: () => ({}),
    tokenGraph: emptyGraph(),
    sourceFiles: [],
    listing: {},
    diagnostics: [],
    cwd: '',
    chrome: {},
    ...partial,
  } as unknown as Project;
}

it('emits a do-not-edit banner + module augmentation', () => {
  const out = renderTokenTypes(fakeProject({}));
  expect(out).toContain('// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.');
  expect(out).toContain("declare module '@unpunnyfuns/swatchbook-addon/hooks'");
  expect(out).toContain('interface SwatchbookTokenMap {');
  // Must carry a top-level `export {}` so the file is a module and the
  // `declare module` augments the real `/hooks` module rather than replacing
  // it. Without this the block shadows every real export (`useToken`, ...)
  // and only breaks in a consumer's real typecheck. Assert it sits at the top
  // level before the block: an `export {}` nested inside `declare module`
  // wouldn't make the file a module, so mere presence isn't enough.
  const lines = out.split('\n');
  const exportIdx = lines.indexOf('export {};');
  const moduleIdx = lines.findIndex((line) =>
    line.startsWith("declare module '@unpunnyfuns/swatchbook-addon/hooks'"),
  );
  expect(exportIdx).toBeGreaterThanOrEqual(0);
  expect(exportIdx).toBeLessThan(moduleIdx);
});

it('sorts token paths alphabetically', () => {
  const project = fakeProject({
    tokenGraph: emptyGraph(['color.bg', 'color.fg', 'color.accent']),
  });
  const out = renderTokenTypes(project);
  const bgIdx = out.indexOf('"color.bg"');
  const accentIdx = out.indexOf('"color.accent"');
  const fgIdx = out.indexOf('"color.fg"');
  expect(accentIdx).toBeLessThan(bgIdx);
  expect(bgIdx).toBeLessThan(fgIdx);
});

it('builds SwatchbookPermutationName as a union of singleton theme names from axes + defaultTuple', () => {
  const project = fakeProject({
    axes: [
      {
        name: 'mode',
        contexts: ['Light', 'Dark'],
        default: 'Light',
        source: 'resolver',
      },
    ],
    defaultTuple: { mode: 'Light' },
  });
  const out = renderTokenTypes(project);
  expect(out).toContain('export type SwatchbookPermutationName = "Light" | "Dark";');
});

it('falls back to string when no axes are present', () => {
  const out = renderTokenTypes(fakeProject({}));
  expect(out).toContain('export type SwatchbookPermutationName = string;');
});

it('includes preset tuples in the theme name union', () => {
  const project = fakeProject({
    axes: [
      { name: 'mode', contexts: ['Light', 'Dark'], default: 'Light', source: 'resolver' },
      {
        name: 'brand',
        contexts: ['Default', 'BrandA'],
        default: 'Default',
        source: 'resolver',
      },
    ],
    defaultTuple: { mode: 'Light', brand: 'Default' },
    presets: [{ name: 'Dark BrandA', axes: { mode: 'Dark', brand: 'BrandA' } }],
  });
  const out = renderTokenTypes(project);
  expect(out).toContain('"Dark · BrandA"');
});

it('emits each path once even when the graph has the path once', () => {
  const project = fakeProject({
    tokenGraph: emptyGraph(['color.bg']),
  });
  const out = renderTokenTypes(project);
  const hits = (out.match(/"color\.bg": string;/g) ?? []).length;
  expect(hits).toBe(1);
});
