import type { Project } from '#/types';
import { emitCss, type EmitCssOptions } from '#/css';

/** Emit the full CSS stylesheet for a project. */
export function projectCss(project: Project, options: EmitCssOptions = {}): string {
  const merged: EmitCssOptions = { ...options };
  if (merged.prefix === undefined && project.config.cssVarPrefix) {
    merged.prefix = project.config.cssVarPrefix;
  }
  return emitCss(project.themes, project.themesResolved, merged);
}

/**
 * Emit a TypeScript module exporting typed unions for token paths and theme
 * names. The preset writes this to `<outDir>/tokens.d.ts` so `useToken()` can
 * autocomplete against the loaded project.
 */
export function emitTypes(project: Project): string {
  const allPaths = new Set<string>();
  for (const theme of project.themes) {
    const tokens = project.themesResolved[theme.name];
    if (!tokens) continue;
    for (const key of Object.keys(tokens)) allPaths.add(key);
  }

  const pathLines = [...allPaths].toSorted().map((p) => `  | ${JSON.stringify(p)}`);
  const themeLines = project.themes.map((t) => JSON.stringify(t.name));

  return `// Generated by @unpunnyfuns/swatchbook-core. Do not edit.

export type TokenPath =
${pathLines.join('\n')};

export const themes = [${themeLines.join(', ')}] as const;
export type ThemeName = (typeof themes)[number];
`;
}
