import type { Project } from '#/types.ts';
import { emitCss, type EmitCssOptions } from '#/css.ts';

/**
 * Emit the full CSS stylesheet for a project.
 *
 * @internal Consumers should not depend on this function. The addon calls
 * it to populate the Storybook virtual module; external consumers driving
 * their own build pipeline should use Terrazzo's CLI against the DTCG
 * sources directly.
 */
export function projectCss(project: Project, options: EmitCssOptions = {}): string {
  const merged: EmitCssOptions = { ...options };
  if (merged.prefix === undefined && project.config.cssVarPrefix) {
    merged.prefix = project.config.cssVarPrefix;
  }
  if (merged.axes === undefined) {
    merged.axes = project.axes;
  }
  if (merged.chrome === undefined) {
    merged.chrome = project.chrome;
  }
  return emitCss(project.permutations, project.permutationsResolved, merged);
}

/**
 * Emit a TypeScript module exporting typed unions for token paths and
 * permutation names. The preset writes this to `<outDir>/tokens.d.ts`
 * so `useToken()` can autocomplete against the loaded project.
 *
 * @internal Consumers should not depend on this function. The addon preset
 * calls it to populate a generated `.d.ts` for `useToken()` autocomplete;
 * external consumers should drive their own typegen from the loaded
 * `Project` if they need something different.
 */
export function emitTypes(project: Project): string {
  const allPaths = new Set<string>();
  for (const perm of project.permutations) {
    const tokens = project.permutationsResolved[perm.name];
    if (!tokens) continue;
    for (const key of Object.keys(tokens)) allPaths.add(key);
  }

  const pathLines = [...allPaths].toSorted().map((p) => `  | ${JSON.stringify(p)}`);
  const permLines = project.permutations.map((p) => JSON.stringify(p.name));

  return `// Generated by @unpunnyfuns/swatchbook-core. Do not edit.

export type TokenPath =
${pathLines.join('\n')};

export const permutations = [${permLines.join(', ')}] as const;
export type PermutationName = (typeof permutations)[number];
`;
}
