/**
 * Build-time bridge between swatchbook tokens and Docusaurus's Infima
 * theme. Loads the DTCG project under `apps/docs/tokens/`, emits the
 * resolved CSS (with a `:root` baseline + per-mode selector blocks), and
 * writes it to `apps/docs/src/css/tokens.generated.css`. `custom.css`
 * imports that file and maps `--ifm-*` variables onto `--sb-color-*`
 * vars so the docs site inherits the same tokens the Storybook addon
 * dogfoods — changes in `apps/docs/tokens/*.json` flow through on
 * rebuild (no manual Infima hex retyping).
 *
 * Runs as a prebuild / prestart step from `apps/docs/package.json`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadProject, projectCss } from '@unpunnyfuns/swatchbook-core';

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = resolve(here, '..');

const project = await loadProject(
  {
    tokens: ['tokens/**/*.json'],
    resolver: 'tokens/resolver.json',
    default: { mode: 'Light' },
    cssVarPrefix: 'sb',
  },
  docsRoot,
);

for (const diagnostic of project.diagnostics) {
  const tag = `[docs:build-tokens:${diagnostic.severity}]`;
  console.warn(`${tag} ${diagnostic.group}: ${diagnostic.message}`);
}

const rawCss = projectCss(project);

/**
 * Rewrite selectors from swatchbook's own scheme (`[data-sb-theme="Light"]`,
 * single-axis form) to Docusaurus's lowercase `[data-theme="light"]` so the
 * per-mode declarations track the Infima theme toggle on `<html>` without
 * any JS glue. Core's single-axis emitter always keys on `theme` regardless
 * of the resolver's axis name — the rewrite handles both casing and the
 * prefix strip.
 */
const css = rawCss
  .replaceAll('[data-sb-theme="Light"]', '[data-theme="light"]')
  .replaceAll('[data-sb-theme="Dark"]', '[data-theme="dark"]');

const outPath = resolve(docsRoot, 'src/css/tokens.generated.css');
await mkdir(dirname(outPath), { recursive: true });
await writeFile(
  outPath,
  `/* Generated by apps/docs/scripts/build-tokens.ts. Do not edit. */\n${css}`,
);

console.log(`[docs:build-tokens] wrote ${outPath}`);
