/**
 * Build-time bridge between swatchbook tokens and Docusaurus's Infima
 * theme. Loads the DTCG project under `apps/docs/tokens/`, emits the
 * resolved CSS (with a `:root` baseline + per-tuple selector blocks),
 * writes it to `apps/docs/src/css/tokens.generated.css`, and emits a
 * small `tokens.snapshot.json` next to it so the navbar switcher can
 * render axes / presets without re-parsing tokens at runtime.
 *
 * `custom.css` imports the CSS; `src/ThemeSwitcher/` imports the JSON.
 * Changes in `apps/docs/tokens/*.json` flow into both outputs on
 * rebuild (no manual Infima hex retyping, no snapshot drift).
 *
 * Runs as a prebuild / prestart step from `apps/docs/package.json`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadProject, projectCss } from '@unpunnyfuns/swatchbook-core';

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = resolve(here, '..');

const project = await loadProject(
  {
    tokens: ['tokens/**/*.json'],
    resolver: 'tokens/resolver.json',
    default: { mode: 'Light', a11y: 'Normal', brand: 'Default' },
    cssVarPrefix: 'sb',
  },
  docsRoot,
);

for (const diagnostic of project.diagnostics) {
  const tag = `[docs:build-tokens:${diagnostic.severity}]`;
  console.warn(`${tag} ${diagnostic.group}: ${diagnostic.message}`);
}

const rawCss = projectCss(project);

/**
 * Rewrite swatchbook's emitter selectors so `mode` tracks Docusaurus's
 * built-in `[data-theme]` toggle on `<html>` (lowercased), while the
 * non-mode axes (`a11y`, `brand`) keep their prefixed `data-sb-<axis>`
 * attributes that the navbar switcher provider owns.
 *
 * Single-axis projects key everything on `theme` regardless of the
 * resolver's axis name (see `selectorFor` in core). Multi-axis keeps
 * the axis name (`mode`, `a11y`, `brand`). Cover both shapes.
 */
const css = rawCss
  .replaceAll('[data-sb-theme="Light"]', '[data-theme="light"]')
  .replaceAll('[data-sb-theme="Dark"]', '[data-theme="dark"]')
  .replaceAll('[data-sb-mode="Light"]', '[data-theme="light"]')
  .replaceAll('[data-sb-mode="Dark"]', '[data-theme="dark"]');

const cssOutPath = resolve(docsRoot, 'src/css/tokens.generated.css');
await mkdir(dirname(cssOutPath), { recursive: true });
await writeFile(
  cssOutPath,
  `/* Generated by apps/docs/scripts/build-tokens.mts. Do not edit. */\n${css}`,
);

/**
 * Minimal switcher snapshot — axes, presets, default tuple, and the
 * css-var prefix. Intentionally drops `themesResolved` (huge and
 * already represented in the emitted CSS) and `diagnostics` (only
 * useful at build time). Lives under src/ so it's bundled with the
 * Docusaurus build rather than fetched at runtime.
 */
interface SwitcherSnapshot {
  axes: {
    name: string;
    contexts: readonly string[];
    default: string;
    description?: string;
    source: 'resolver' | 'layered' | 'synthetic';
  }[];
  presets: {
    name: string;
    axes: Partial<Record<string, string>>;
    description?: string;
  }[];
  defaults: Record<string, string>;
  cssVarPrefix: string;
}

const snapshot: SwitcherSnapshot = {
  axes: project.axes.map((axis) => {
    const entry: SwitcherSnapshot['axes'][number] = {
      name: axis.name,
      contexts: axis.contexts,
      default: axis.default,
      source: axis.source,
    };
    if (axis.description !== undefined) entry.description = axis.description;
    return entry;
  }),
  presets: project.presets.map((preset) => {
    const entry: SwitcherSnapshot['presets'][number] = {
      name: preset.name,
      axes: preset.axes,
    };
    if (preset.description !== undefined) entry.description = preset.description;
    return entry;
  }),
  defaults: Object.fromEntries(project.axes.map((axis) => [axis.name, axis.default])),
  cssVarPrefix: project.config.cssVarPrefix ?? 'sb',
};

const jsonOutPath = resolve(docsRoot, 'src/tokens.snapshot.json');
await writeFile(jsonOutPath, `${JSON.stringify(snapshot, null, 2)}\n`);

console.log(`[docs:build-tokens] wrote ${cssOutPath}`);
console.log(`[docs:build-tokens] wrote ${jsonOutPath}`);
