import type { CSSProperties } from 'react';
import {
  BORDER_DEFAULT,
  BORDER_FAINT,
  BORDER_STRONG,
  MONO_STACK,
  SURFACE_MUTED,
  SURFACE_RAISED,
  TEXT_DEFAULT,
  TEXT_MUTED,
  surfaceStyle,
} from '#/internal/styles.tsx';

export const styles = {
  wrapper: {
    ...surfaceStyle,
    padding: 16,
    border: BORDER_DEFAULT,
  } satisfies CSSProperties,
  heading: {
    margin: 0,
    fontFamily: MONO_STACK,
    fontSize: 16,
  } satisfies CSSProperties,
  subline: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '4px 0 12px',
    fontSize: 12,
    opacity: 0.8,
  } satisfies CSSProperties,
  typePill: {
    display: 'inline-block',
    padding: '2px 6px',
    borderRadius: 4,
    fontSize: 10,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    background: SURFACE_MUTED,
  } satisfies CSSProperties,
  description: {
    margin: '0 0 12px',
    opacity: 0.85,
  } satisfies CSSProperties,
  sectionHeader: {
    fontFamily: MONO_STACK,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    opacity: 0.6,
    margin: '12px 0 6px',
  } satisfies CSSProperties,
  chain: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
    fontFamily: MONO_STACK,
    fontSize: 12,
  } satisfies CSSProperties,
  chainNode: {
    padding: '2px 6px',
    borderRadius: 4,
    border: BORDER_DEFAULT,
  } satisfies CSSProperties,
  arrow: {
    opacity: 0.5,
  } satisfies CSSProperties,
  themeTable: {
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    fontSize: 12,
  } satisfies CSSProperties,
  themeRow: {
    borderBottom: BORDER_FAINT,
  } satisfies CSSProperties,
  themeCell: {
    padding: '6px 8px',
    verticalAlign: 'middle',
  } satisfies CSSProperties,
  swatch: {
    display: 'inline-block',
    width: 14,
    height: 14,
    verticalAlign: 'middle',
    marginRight: 6,
    borderRadius: 3,
    border: BORDER_DEFAULT,
  } satisfies CSSProperties,
  snippet: {
    display: 'block',
    padding: '8px 10px',
    borderRadius: 4,
    background: SURFACE_MUTED,
    fontFamily: MONO_STACK,
    fontSize: 12,
    whiteSpace: 'pre',
    overflow: 'auto',
  } satisfies CSSProperties,
  missing: {
    padding: 12,
    opacity: 0.7,
  } satisfies CSSProperties,
  typographySample: {
    padding: '8px 0',
  } satisfies CSSProperties,
  shadowSample: {
    width: 140,
    height: 56,
    background: SURFACE_RAISED,
    border: BORDER_FAINT,
    borderRadius: 6,
  } satisfies CSSProperties,
  borderSample: {
    width: 140,
    height: 56,
    background: SURFACE_RAISED,
    borderRadius: 6,
  } satisfies CSSProperties,
  gradientSample: {
    width: 220,
    height: 56,
    borderRadius: 6,
    border: BORDER_FAINT,
  } satisfies CSSProperties,
  strokeStyleLine: {
    height: 0,
    borderTopWidth: 4,
    borderTopColor: TEXT_DEFAULT,
    width: 220,
  } satisfies CSSProperties,
  strokeStyleSvg: {
    width: 220,
    height: 24,
    color: TEXT_DEFAULT,
  } satisfies CSSProperties,
  strokeStyleFallback: {
    fontFamily: MONO_STACK,
    fontSize: 12,
    color: TEXT_MUTED,
  } satisfies CSSProperties,
  colorSwatchRow: {
    display: 'flex',
    gap: 1,
    borderRadius: 6,
    overflow: 'hidden',
    border: BORDER_DEFAULT,
    width: 220,
    height: 56,
  } satisfies CSSProperties,
  colorSwatchLight: {
    flex: 1,
    boxShadow: 'inset 0 0 0 8px rgba(255, 255, 255, 0.9)',
  } satisfies CSSProperties,
  colorSwatchDark: {
    flex: 1,
    boxShadow: 'inset 0 0 0 8px rgba(17, 17, 17, 0.9)',
  } satisfies CSSProperties,
  breakdownSection: {
    fontFamily: MONO_STACK,
    fontSize: 12,
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    columnGap: 12,
    rowGap: 3,
    marginTop: 6,
  } satisfies CSSProperties,
  breakdownKey: {
    color: TEXT_MUTED,
  } satisfies CSSProperties,
  breakdownLayerHeader: {
    gridColumn: '1 / -1',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: TEXT_MUTED,
    marginTop: 4,
  } satisfies CSSProperties,
  fontFamilySample: {
    padding: '4px 0',
    fontSize: 22,
    lineHeight: 1.2,
  } satisfies CSSProperties,
  fontWeightSample: {
    padding: '4px 0',
    fontSize: 32,
    lineHeight: 1,
  } satisfies CSSProperties,
  dimensionTrack: {
    display: 'flex',
    alignItems: 'center',
    height: 32,
    maxWidth: '100%',
    overflow: 'hidden',
  } satisfies CSSProperties,
  dimensionBar: {
    height: 16,
    background: 'var(--sb-color-sys-accent-bg, #3b82f6)',
    borderRadius: 3,
    maxWidth: '100%',
  } satisfies CSSProperties,
  motionTrack: {
    position: 'relative',
    height: 32,
    width: '100%',
    maxWidth: 320,
    background: SURFACE_MUTED,
    borderRadius: 16,
    overflow: 'hidden',
  } satisfies CSSProperties,
  motionBall: {
    position: 'absolute',
    top: '50%',
    width: 24,
    height: 24,
    marginTop: -12,
    borderRadius: '50%',
    background: 'var(--sb-color-sys-accent-bg, #3b82f6)',
  } satisfies CSSProperties,
  aliasedByList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    fontFamily: MONO_STACK,
    fontSize: 12,
  } satisfies CSSProperties,
  aliasedByRow: {
    padding: '2px 0',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  } satisfies CSSProperties,
  aliasedByTruncated: {
    fontSize: 11,
    opacity: 0.6,
    fontStyle: 'italic',
    marginTop: 4,
  } satisfies CSSProperties,
  reducedMotion: {
    fontSize: 11,
    color: TEXT_MUTED,
    fontStyle: 'italic',
  } satisfies CSSProperties,
  tupleIndicator: {
    fontSize: 11,
    opacity: 0.7,
    margin: '0 0 6px',
    fontFamily: MONO_STACK,
  } satisfies CSSProperties,
  consumerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    marginBottom: 4,
    borderRadius: 4,
    background: SURFACE_MUTED,
  } satisfies CSSProperties,
  consumerRowLabel: {
    fontFamily: MONO_STACK,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    opacity: 0.6,
    minWidth: 32,
    flexShrink: 0,
  } satisfies CSSProperties,
  consumerRowValue: {
    flex: 1,
    fontFamily: MONO_STACK,
    fontSize: 12,
    whiteSpace: 'nowrap',
    overflow: 'auto',
  } satisfies CSSProperties,
  consumerRowCopy: {
    padding: '3px 8px',
    fontSize: 11,
    fontFamily: MONO_STACK,
    background: SURFACE_RAISED,
    color: TEXT_DEFAULT,
    border: BORDER_STRONG,
    borderRadius: 4,
    cursor: 'pointer',
    flexShrink: 0,
  } satisfies CSSProperties,
};
