import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Project } from '@unpunnyfuns/swatchbook-core';
import { emitTypes, loadProject, projectCss } from '@unpunnyfuns/swatchbook-core';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, 'dist');

const CSS_VAR_PREFIX = 'sb';

await rm(dist, { recursive: true, force: true });
await mkdir(resolve(dist, 'css'), { recursive: true });
await mkdir(resolve(dist, 'themes'), { recursive: true });

const project = await loadProject(
  {
    tokens: ['tokens/**/*.json'],
    themes: [
      {
        name: 'Light',
        layers: ['tokens/ref/**/*.json', 'tokens/sys/**/*.json', 'tokens/themes/light.json'],
      },
    ],
    default: 'Light',
    cssVarPrefix: CSS_VAR_PREFIX,
  },
  here,
);

// 1. Single stylesheet with all [data-theme] blocks
await writeFile(resolve(dist, 'css/index.css'), projectCss(project));

// 2. Per-theme resolved JSON — `$value` only, keyed by token path
await Promise.all(
  project.themes.map(async (theme) => {
    const tokens = project.themesResolved[theme.name] ?? {};
    const values: Record<string, unknown> = {};
    for (const [path, token] of Object.entries(tokens)) {
      values[path] = token.$value;
    }
    await writeFile(
      resolve(dist, `themes/${theme.name}.json`),
      `${JSON.stringify(values, null, 2)}\n`,
    );
  }),
);

// 3. Runtime entry (.mjs) — typed cssVars map + token() helper + themes list
await writeFile(resolve(dist, 'index.mjs'), renderRuntime(project, CSS_VAR_PREFIX));

// 4. Type declarations (.d.mts) — path union, theme names, typed cssVars + token()
await writeFile(resolve(dist, 'index.d.mts'), renderTypes(project));

const themeCount = project.themes.length;
const tokenCount = Object.keys(project.graph).length;
console.log(`tokens-starter: built ${themeCount} theme(s), ${tokenCount} tokens → dist/`);

function renderRuntime(proj: Project, prefix: string): string {
  const keys = collectTokenPaths(proj).toSorted();
  const entries = keys.map(
    (k) =>
      `  ${JSON.stringify(k)}: ${JSON.stringify(`var(--${prefix}-${k.replaceAll('.', '-')})`)},`,
  );
  const themeLines = proj.themes.map((t) => JSON.stringify(t.name));
  return `// Generated by @unpunnyfuns/swatchbook-tokens/build.ts. Do not edit.

export const cssVars = Object.freeze({
${entries.join('\n')}
});

export function token(path) {
  return cssVars[path];
}

export const themes = Object.freeze([${themeLines.join(', ')}]);
`;
}

function renderTypes(proj: Project): string {
  const schema = emitTypes(proj);
  return `${schema}
export declare const cssVars: Readonly<Record<TokenPath, string>>;
export declare function token(path: TokenPath): string;
`;
}

function collectTokenPaths(proj: Project): string[] {
  const all = new Set<string>();
  for (const theme of proj.themes) {
    const tokens = proj.themesResolved[theme.name];
    if (!tokens) continue;
    for (const key of Object.keys(tokens)) all.add(key);
  }
  return [...all];
}
