import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Config, Project } from '@unpunnyfuns/swatchbook-core';
import { loadProject } from '@unpunnyfuns/swatchbook-core';
import { enumerateThemes } from '@unpunnyfuns/swatchbook-core/themes';
import { createJiti } from 'jiti';
import type { InlineConfig } from 'vite';
import type { AddonOptions } from '#/options.ts';
import { swatchbookTokensPlugin } from '#/virtual/plugin.ts';

interface PresetOptions extends AddonOptions {
  /** Storybook injects this — the `.storybook` directory absolute path. */
  configDir: string;
}

/**
 * Storybook preset entry. Called by Storybook at config time; extends Vite's
 * plugin list with our virtual-module plugin so the preview can import
 * `virtual:swatchbook/tokens`. Also writes the typed token-path codegen so
 * `useToken()` autocompletes against the loaded project.
 */
export async function viteFinal(
  viteConfig: InlineConfig,
  options: PresetOptions,
): Promise<InlineConfig> {
  const { config, cwd } = await resolveConfig(options);

  // One `loadProject` call shared between codegen (needs the resolved
  // shape to render typed token paths) and the Vite plugin (uses it
  // for its first virtual-module render). Without sharing, the addon
  // calls `loadProject` twice at Storybook startup — once here for
  // codegen, once again inside the plugin's `buildStart`.
  const project = await loadProject(config, cwd);
  await writeTokenCodegen(project, options);

  const plugins = Array.isArray(viteConfig.plugins) ? [...viteConfig.plugins] : [];
  plugins.push(
    swatchbookTokensPlugin({
      config,
      cwd,
      initialProject: project,
      ...(options.integrations !== undefined && { integrations: options.integrations }),
    }),
  );

  return { ...viteConfig, plugins };
}

/** Storybook appends this module into the manager bundle so our toolbar tool registers. */
export function managerEntries(entry: string[] = []): string[] {
  const managerUrl = import.meta.resolve('@unpunnyfuns/swatchbook-addon/manager');
  return [...entry, fileURLToPath(managerUrl)];
}

async function resolveConfig(options: PresetOptions): Promise<{ config: Config; cwd: string }> {
  const projectRoot = resolve(options.configDir, '..');

  if (options.config) {
    return { config: options.config, cwd: projectRoot };
  }

  const path = options.configPath ?? 'swatchbook.config.ts';
  const absolute = isAbsolute(path) ? path : resolve(options.configDir, path);

  const jiti = createJiti(pathToFileURL(options.configDir).href, {
    interopDefault: true,
    moduleCache: false,
  });
  const loaded = (await jiti.import(absolute, { default: true })) as Config;

  // If the config file isn't at projectRoot, still resolve globs from its dir.
  const cwd = dirname(absolute);
  return { config: loaded, cwd };
}

async function writeTokenCodegen(project: Project, options: PresetOptions): Promise<void> {
  const projectRoot = resolve(options.configDir, '..');
  const outDir = resolve(projectRoot, project.config.outDir ?? '.swatchbook');
  await mkdir(outDir, { recursive: true });
  const content = renderTokenTypes(project);
  await writeFile(resolve(outDir, 'tokens.d.ts'), content);
}

/** @internal Exported for tests; not part of the public API. */
export function renderTokenTypes(project: Project): string {
  const sorted = [...project.varianceByPath.keys()].toSorted();
  const tokenEntries = sorted.map((p) => `    ${JSON.stringify(p)}: string;`);
  const themeNames = project.axes.length === 0 ? [] : enumerateThemes(project).map((t) => t.name);
  const themeUnion =
    themeNames.length > 0 ? themeNames.map((n) => JSON.stringify(n)).join(' | ') : 'string';

  return [
    '// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.',
    "declare module '@unpunnyfuns/swatchbook-addon/hooks' {",
    '  interface SwatchbookTokenMap {',
    ...tokenEntries,
    '  }',
    '',
    `  export type SwatchbookPermutationName = ${themeUnion};`,
    '}',
    '',
  ].join('\n');
}
