import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Config, Project } from '@unpunnyfuns/swatchbook-core';
import { loadProject } from '@unpunnyfuns/swatchbook-core';
import { createJiti } from 'jiti';
import type { InlineConfig } from 'vite';
import type { AddonOptions } from '#/options.ts';
import { swatchbookTokensPlugin } from '#/virtual/plugin.ts';

interface PresetOptions extends AddonOptions {
  /** Storybook injects this — the `.storybook` directory absolute path. */
  configDir: string;
}

/**
 * Storybook preset entry. Called by Storybook at config time; extends Vite's
 * plugin list with our virtual-module plugin so the preview can import
 * `virtual:swatchbook/tokens`. Also writes the typed token-path codegen so
 * `useToken()` autocompletes against the loaded project.
 */
export async function viteFinal(
  viteConfig: InlineConfig,
  options: PresetOptions,
): Promise<InlineConfig> {
  const { config, cwd } = await resolveConfig(options);

  // Codegen runs once at Vite startup. The virtual module plugin still
  // owns the live reload path via its HMR watcher; this file just gives
  // TS autocomplete for `useToken('…')` in consumer stories.
  await writeTokenCodegen(config, cwd, options);

  const plugins = Array.isArray(viteConfig.plugins) ? [...viteConfig.plugins] : [];
  plugins.push(swatchbookTokensPlugin({ config, cwd }));

  return { ...viteConfig, plugins };
}

/** Storybook appends this module into the manager bundle so our toolbar tool registers. */
export function managerEntries(entry: string[] = []): string[] {
  const managerUrl = import.meta.resolve('@unpunnyfuns/swatchbook-addon/manager');
  return [...entry, fileURLToPath(managerUrl)];
}

async function resolveConfig(options: PresetOptions): Promise<{ config: Config; cwd: string }> {
  const projectRoot = resolve(options.configDir, '..');

  if (options.config) {
    return { config: options.config, cwd: projectRoot };
  }

  const path = options.configPath ?? 'swatchbook.config.ts';
  const absolute = isAbsolute(path) ? path : resolve(options.configDir, path);

  const jiti = createJiti(pathToFileURL(options.configDir).href, {
    interopDefault: true,
    moduleCache: false,
  });
  const loaded = (await jiti.import(absolute, { default: true })) as Config;

  // If the config file isn't at projectRoot, still resolve globs from its dir.
  const cwd = dirname(absolute);
  return { config: loaded, cwd };
}

async function writeTokenCodegen(
  config: Config,
  cwd: string,
  options: PresetOptions,
): Promise<void> {
  const project = await loadProject(config, cwd);
  const projectRoot = resolve(options.configDir, '..');
  const outDir = resolve(projectRoot, config.outDir ?? '.swatchbook');
  await mkdir(outDir, { recursive: true });
  const content = renderTokenTypes(project);
  await writeFile(resolve(outDir, 'tokens.d.ts'), content);
}

/** @internal Exported for tests; not part of the public API. */
export function renderTokenTypes(project: Project): string {
  const paths = new Set<string>();
  for (const theme of project.themes) {
    const tokens = project.themesResolved[theme.name];
    if (!tokens) continue;
    for (const path of Object.keys(tokens)) paths.add(path);
  }
  const sorted = [...paths].toSorted();
  const tokenEntries = sorted.map((p) => `    ${JSON.stringify(p)}: string;`);
  const themeUnion = project.themes.map((t) => JSON.stringify(t.name)).join(' | ') || 'string';

  return [
    '// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.',
    "declare module '@unpunnyfuns/swatchbook-addon/hooks' {",
    '  interface SwatchbookTokenMap {',
    ...tokenEntries,
    '  }',
    '',
    `  export type SwatchbookThemeName = ${themeUnion};`,
    '}',
    '',
  ].join('\n');
}
