import type { Project } from '@unpunnyfuns/swatchbook-core';
import { listPaths } from '@unpunnyfuns/swatchbook-core/graph';
import { enumerateThemes } from '@unpunnyfuns/swatchbook-core/themes';

/**
 * Renders the `.swatchbook/tokens.d.ts` module augmentation body: every
 * token path as a `SwatchbookTokenMap` field, plus a `SwatchbookPermutationName`
 * union of composed theme names. Called by `viteFinal` at preset time; kept
 * out of `preset.ts` (a tsdown entry) so it isn't reachable from the public
 * `./preset` subpath.
 */
export function renderTokenTypes(project: Project): string {
  const sorted = [...listPaths(project.tokenGraph)].toSorted();
  const tokenEntries = sorted.map((p) => `    ${JSON.stringify(p)}: string;`);
  const themeNames = project.axes.length === 0 ? [] : enumerateThemes(project).map((t) => t.name);
  const themeUnion =
    themeNames.length > 0 ? themeNames.map((n) => JSON.stringify(n)).join(' | ') : 'string';

  return [
    '// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.',
    // `export {}` makes this file a module, so the `declare module` below is a
    // module AUGMENTATION (merging into the real `/hooks` module) rather than
    // an ambient replacement. Without it the block shadows the real module and
    // erases every export it declares (`useToken`, `TokenInfo`, ...), which
    // only surfaces in a consumer's real typecheck, not in local dev.
    'export {};',
    "declare module '@unpunnyfuns/swatchbook-addon/hooks' {",
    '  interface SwatchbookTokenMap {',
    ...tokenEntries,
    '  }',
    '',
    `  export type SwatchbookPermutationName = ${themeUnion};`,
    '}',
    '',
  ].join('\n');
}
